---
- name: Create .config/ranger/ directory
  become: true
  ansible.builtin.file:
    path: "/home/{{ item }}/.config/ranger"
    state: directory
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: '0644'
    recurse: true
  loop: "{{ accounts }}"
  when:
    - dotfiles__ranger_hidden_files | bool
    - accounts is defined
    - accounts != ['root']
    - accounts != 'root'

- name: Create .config/ranger/rc.conf file
  become: true
  ansible.builtin.template:
    src: templates/ranger_rc.conf.j2
    dest: "/home/{{ item }}/.config/ranger/rc.conf"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: '0644'
  loop: "{{ accounts }}"
  when:
    - dotfiles__ranger_hidden_files | bool
    - accounts is defined
    - accounts != ['root']
    - accounts != 'root'
