---
- name: Copy vimrc configuration to root
  become: true
  ansible.builtin.copy:
    src: 'templates/tmux.conf.j2'
    dest: '/root/.tmux.conf'
    owner: root
    group: root
    mode: 'u=rw,g=r,o='

- name: Copy vimrc configuration to non admin users
  become: true
  ansible.builtin.copy:
    src: 'templates/tmux.conf.j2'
    dest: '/home/{{ item }}/.tmux.conf'
    owner: '{{ item }}'
    group: '{{ item }}'
    mode: 'u=rw,g=r,o='
  loop: "{{ accounts }}"
  when:
    - accounts is defined
    - accounts != ['root']
    - accounts != 'root'
