# .bashrc

# Source global definitions
if [ -f /etc/bash.bashrc ]; then
	. /etc/bash.bashrc
fi

# User specific environment
PATH="$HOME/.local/bin:$HOME/bin:$PATH"
export PATH

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
{% for alias in base__aliases %}
{% if alias.color %}
    alias {{ alias.alias }}="{{ alias.command }} --color=auto"
{% endif%}
{% endfor %}
fi

{% for alias in base__aliases %}
{% if not alias.color %}
    alias {{ alias.alias }}="{{ alias.command }}"
{% endif%}
{% endfor %}

# hostory controll
HISTCONTROL={{ base__history_control }}
shopt -s histappend
HISTSIZE={{ base__history_size }}
HISTFILESIZE={{ base__history_file_size }}

{% for _row in base__additional_user_bashrc_lines | default() %}
{{ _row }}
{% endfor %}

{% for custom in base__custom_config %}
{% if custom.user == item %}
{{ custom.cmd }}
{% endif %}
{% endfor %}

# vim:ts=4:sw=4
