" gopass secure editor
au BufNewFile,BufRead /dev/shm/gopass.* setlocal noswapfile nobackup noundofile

" vim layout
syntax on               " enable syntax highlighting
set cursorline          " highlight the current line
set fileencoding=utf-8
set encoding=utf-8
colorscheme elflord
set cursorline          " highlight the current line

" tabs and indenting
set autoindent          " auto indenting
set smartindent         " smart indenting
set expandtab           " spaces instead of tabs
set tabstop=2           " 2 spaces for tabs
set shiftwidth=2        " 2 spaces for indentation

" mouse
set mouse-=a            " disable weird mouse behavior
nnoremap <C-Left> :tabprevious<CR>
nnoremap <C-h> :tabprevious<CR>
nnoremap <C-Right> :tabnext<CR>
nnoremap <C-l> :tabnext<CR>

" bells
set noerrorbells        " turn off audio bell
set visualbell          " but leave on a visual bell

" search
set hlsearch            " highlighted search results
set showmatch           " show matching bracket

" behavior
filetype on             " enable filetype detection
set scrolloff=5         " show at least 5 lines above/below
set showcmd             " show selection metadata
set showmode            " show INSERT, VISUAL, etc. mode
set showmatch           " show matching brackets
set autoindent smartindent  " auto/smart indent
set smarttab            " better backspace and tab functionali
set nobackup            " don't create pointless backup files; Use VCS instead
set autoread            " watch for file changes

" extra whitespace
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
