set expandtab
set tabstop=4 
set shiftwidth=4
set fileencoding=utf-8 
set encoding=utf-8
colorscheme elflord 
syntax on
set mouse-=a
nnoremap <C-Left> :tabprevious<CR>
nnoremap <C-h> :tabprevious<CR>
nnoremap <C-Right> :tabnext<CR>
nnoremap <C-l> :tabnext<CR>
